### ISSUE TITLE
IdentityServer: Is't into this template?

### ISSUE THREAD

**Issue by biapar** [proudmonkey/ApiBoilerPlate#18]
Hi,

I not understand if identity server is into this template or I've to create an external project and put in.
Could you explain?
Thanks.

**Comment by proudmonkey** [comment]
Hi @biapar ,

Thanks for your interest on using the template. IDS is assumed to be a separate project. Here's an article that I wrote about it: https://vmsdurano.com/apiboilerplate-and-identityserver4-access-control-for-apis/

**Comment by biapar** [comment]
So this IdentityServer4.AccessTokenValidation - For JWT Authentication handling is used only as client. It's right?

**Comment by proudmonkey** [comment]
Yep
