### ISSUE TITLE
HealthChecksUI not start

### ISSUE THREAD

**Issue by biapar** [proudmonkey/ApiBoilerPlate#20]
I start the project and try to open HealthChecksUI. I don't see the UI.

`"HealthChecksUI": {
    "HealthChecks": [
      {
        "Name": "HTTP-Api-Basic",
        "Uri": "https://localhost:5001/selfcheck"
      }
    ],
    "Webhooks": [
      {
        "Name": "",
        "Uri": "",
        "Payload": "",
        "RestoredPayload": ""
      }
    ],
    "EvaluationTimeInSeconds": 10,
    "MinimumSecondsBetweenFailureNotifications": 60,
    "HealthCheckDatabaseConnectionString": "Data Source=Infrastructure\\HealthChecks\\Db\\healthchecksdb"
  }`

**Comment by proudmonkey** [comment]
You have to navigate to `/healthchecks-iu`. For details about the template improvements, see: https://vmsdurano.com/apiboilerplate-new-features-and-improvements-for-building-asp-net-core-3-apis/

**Comment by improwise** [comment]
Please note that the correct path is healthchecks-ui (ui, not iu). The same typo exists in the article if I remember correctly.

**Comment by proudmonkey** [comment]
Ah good catch on the typo. I've corrected the article. Thanks!

**Comment by biapar** [comment]
I confirm that it works

![image](https://user-images.githubusercontent.com/661517/99985786-b047ff80-2dae-11eb-88ca-29b6b0a6b5f2.png)
