### ISSUE TITLE
Runtime problem after updating AspNetCoreRateLimit to 4.0+ (with solution)

### ISSUE THREAD

**Issue by improwise** [proudmonkey/ApiBoilerPlate#26]
If you run into problems like this after updating AspNetCoreRateLimit (or have it updated for you by another NuGet package):

System.InvalidOperationException: Unable to resolve service for type 'AspNetCoreRateLimit.IProcessingStrategy' while attempting to activate 'AspNetCoreRateLimit.IpRateLimitMiddleware'.

This is the solution needed to get it working again:

            // See release notes for 4.0.0 https://github.com/stefanprodan/AspNetCoreRateLimit/releases
            services.AddSingleton<IProcessingStrategy, AsyncKeyLockProcessingStrategy>();

In RegisterRequestRateLimiter class

**Comment by proudmonkey** [comment]
Thank you for sharing the solution ❤️
