### ISSUE TITLE
Usinng this with angular 2+

### ISSUE THREAD

**Issue by LucaGabi** [proudmonkey/ApiBoilerPlate#5]
Hi, I would be grateful if you could show small sample on how to integrate this with an angular 2+ client application.

Thanks.

**Comment by proudmonkey** [comment]
I wish I have time to do that, but here's what you can do. You will build an API using this template and then host it somewhere wherein your Angular app can access to it. You will then need to import the required modules to make an HTTP requests. See this for example:https://www.red-gate.com/simple-talk/dotnet/net-development/building-an-angularjs-application-with-asp-net-core/
